persist env; bail on failed install

diff --git a/dev-container b/dev-container
--- a/dev-container
+++ b/dev-container
@@ -52,10 +52,14 @@ EOF
 
 echo "PROJECT_DIR: $PROJECT_DIR"
 
-sudo docker compose pull
+sudo -E docker compose pull
 
 if [ "$DO_INSTALL" = true ]; then
-    sudo docker compose up install
+    sudo -E docker compose up --exit-code-from install install
+    if [ $? -ne 0 ]; then
+        echo "ERROR: Install failed. Not starting services."
+        exit 1
+    fi
 fi
 
-sudo docker compose up web db
+sudo -E docker compose up web db
